<?php

/**
 * Implements hook_theme()
 */
function iish_conference_personalpage_theme() {
  return array(
    'iish_conference_personalpage_upload_paper' => array(
      'variables' => array(
        'paper' => NULL,
        'paperDownloadLink' => NULL,
        'actionUrl' => NULL,
        'maxSize' => NULL,
        'extensions' => NULL,
        'deleteForm' => NULL,
        'backUrl' => NULL,
        'backLink' => NULL,
      ),
    ),
  );
}
